---
name: pointofsales
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  dio: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^0.23.0+1
  flutter_blue: ^0.8.0
  ndialog: ^4.1.0
  pull_to_refresh: ^2.0.0
  lottie: ^1.1.0
  find_dropdown: ^1.0.0
  syncfusion_flutter_datepicker: ^19.2.51
  intl: ^0.17.0
  image_picker: ^0.8.4+2
  flutter_image_compress: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  blue_thermal_printer: ^1.1.8
  open_settings: ^2.0.2
  in_app_update: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: ^10.0.9
  firebase_core: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
